# Generated by Django 4.0 on 2021-12-17 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shorty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=10, unique=True)),
                ('url', models.URLField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(db_column='session_key', on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
            ],
        ),
    ]
