# Generated by Django 4.0 on 2021-12-17 10:18

import apps.shorty.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorty',
            name='link',
            field=models.CharField(default=apps.shorty.utils.get_link, max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator('^[A-Za-z0-9]+$', message='Link must be letters and numbers.')]),
        ),
    ]
